### PR TITLE
tidied/culled extraneous proj files, converted to arc, etc

### PR DESCRIPTION
**Pull request by mralexgray**

### CODE REVIEW

**Comment by colincornaby** [comment]
This didn't build for me. It looks like the linking to Cocoa and OpenGL has been removed?

**Comment by mralexgray** [comment]
Are you using Xcode 5+ / 10.8 or higher SDK?  I enabled Modules... which does all that automatically on `#import`...  looks like those changes didn't get pushed, sorry bout that.  try that.

screen shot 2014-08-20 at 4 21 40 am

**Comment by colincornaby** [comment]
Haven't lost track of this, I'm also just looking at fixes for Retina displays and modernizing a bit more. Originally when I wrote this I was looking at supporting back to older versions of OS X, but I think it's fair to move to CADisplayLink now.

**Comment by colincornaby** [comment]
Check out the develop branch. I'll probably merge it into master soon and then look at integrating your changes. The changes in develop clean up a lot of stuff.

**Comment by colincornaby** [comment]
Been a long time! I'm going to start work on porting this to Metal so I'll go ahead and accept these changes.

**Comment by mralexgray** [comment]
Wow. Glad to know some of the dumb things I choose to waste my time with... occasionally  bear fruit!  No offense intended!  

Fuck metal, though. Mojave’s sys reqs are... offensive.

**Comment by colincornaby** [comment]
Planning on keeping the OpenGL version working as well, so if Metal isn't your thing that version will stick around.

**Pull request merged**
